I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 34, in script
    play music Generic_Filler.wav
  File "renpy/common/000statements.rpy", line 120, in execute_play_music
    renpy.music.play(_audio_eval(p["file"]),
  File "renpy/common/000statements.rpy", line 32, in _audio_eval
    return eval(expr, locals=store.audio.__dict__)
  File "game/script.rpy", line 34, in <module>
    play music Generic_Filler.wav
NameError: name 'Generic_Filler' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 34, in script
    play music Generic_Filler.wav
  File "C:\Users\Kyle\Desktop\Renpy\renpy-7.0.0-sdk\renpy\ast.py", line 1828, in execute
    self.call("execute")
  File "C:\Users\Kyle\Desktop\Renpy\renpy-7.0.0-sdk\renpy\ast.py", line 1816, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "C:\Users\Kyle\Desktop\Renpy\renpy-7.0.0-sdk\renpy\statements.py", line 177, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 120, in execute_play_music
    renpy.music.play(_audio_eval(p["file"]),
  File "renpy/common/000statements.rpy", line 32, in _audio_eval
    return eval(expr, locals=store.audio.__dict__)
  File "C:\Users\Kyle\Desktop\Renpy\renpy-7.0.0-sdk\renpy\python.py", line 1943, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\Kyle\Desktop\Renpy\renpy-7.0.0-sdk\renpy\python.py", line 1936, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 34, in <module>
    play music Generic_Filler.wav
NameError: name 'Generic_Filler' is not defined

Windows-8-6.2.9200
Ren'Py 7.0.0.196
Testing Grounds 1.0
Fri Jul 20 20:19:43 2018
